-- MySQL Script generated by MySQL Workbench
-- Tue Nov  5 18:39:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema amazon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amazon` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `amazon` ;

-- -----------------------------------------------------
-- Table `amazon`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazon`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(600) NULL,
  `published_at` VARCHAR(45) NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazon`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `sex` CHAR(1) NULL,
  `name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazon`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `books_book_id` INT NOT NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `fk_cart_books_idx` (`books_book_id` ASC) VISIBLE,
  INDEX `fk_cart_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_books`
    FOREIGN KEY (`books_book_id`)
    REFERENCES `amazon`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `amazon`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazon`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `ordercol` VARCHAR(45) NULL,
  `users_user_id` INT NOT NULL,
  `books_book_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_orders_books1_idx` (`books_book_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `amazon`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_books1`
    FOREIGN KEY (`books_book_id`)
    REFERENCES `amazon`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazon`.`authors` (
  `authors_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(5) NULL,
  PRIMARY KEY (`authors_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amazon`.`authors_has_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amazon`.`authors_has_books` (
  `authors_authors_id` INT NOT NULL,
  `books_book_id` INT NOT NULL,
  PRIMARY KEY (`authors_authors_id`, `books_book_id`),
  INDEX `fk_authors_has_books_books1_idx` (`books_book_id` ASC) VISIBLE,
  INDEX `fk_authors_has_books_authors1_idx` (`authors_authors_id` ASC) VISIBLE,
  CONSTRAINT `fk_authors_has_books_authors1`
    FOREIGN KEY (`authors_authors_id`)
    REFERENCES `amazon`.`authors` (`authors_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authors_has_books_books1`
    FOREIGN KEY (`books_book_id`)
    REFERENCES `amazon`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
